name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true